name: Outdated dependencies

permissions:
    contents: read

on:
    push:
        branches: [ "main" ]
    schedule:
        -   cron: '0 21 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    antq:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout
                uses: actions/checkout@v7
                with:
                    fetch-depth: 1

            -   name: Check for outdated dependencies
                uses: liquidz/antq-action@38f06c10868db5394bf46d3fe938bb027acd7272
                with:
                    excludes: 'technomancy/leiningen'
